/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'color-h1': 'var(--iq-h1-color)',
        'color-h2': 'var(--iq-h2-color)',
        'color-p': 'var(--iq-p-color)',
        'color-border': 'var(--iq-border-color)',
        'color-link': 'var(--iq-link-color)',
        'color-hr': 'var(--iq-border-color)',
        'color-card': 'var(--iq-card-color)',
        'color-stage': 'var(--iq-stage-color)',
        'color-stage-border': 'var(--iq-stage-border-color)',
        'color-cell': 'var(--iq-cell-color)',
        'color-label': 'var(--iq-label-color)',
        'color-input': 'var(--iq-cell-color)',
        'color-input-border': 'var(--iq-input-border-color)',
        'color-danger': 'var(--iq-danger-color)',
        'color-warning': 'var(--iq-warning-color)',
        'color-cancel': 'var(--iq-cancel-color)',
        'color-success': 'var(--iq-success-color)',
        'color-action': 'var(--iq-action-color)',
        'color-brand': 'var(--iq-brand-color)',
        'color-badge': 'var(--iq-badge-color)',
        'color-active': 'var(--iq-active-color)',
        'color-favorite': 'var(--iq-favorite-color)',
        'color-card-overlay': 'var(--iq-active-nav-bg-color)',
        'color-overlay': 'var(--iq-overlay-color)',
        'color-infobox': 'var(--iq-infobox-color)',
        'color-pipe': 'var(--iq-pipe-color)',
        'color-muted2': 'var(--iq-muted2-color)',
        'color-muted3': 'var(--iq-muted3-color)',
        'gray-50': 'var(--iq-gray-50)',
        'gray-100': 'var(--iq-gray-100)',
        'gray-200': 'var(--iq-gray-200)',
        'gray-300': 'var(--iq-gray-300)',
        'gray-400': 'var(--iq-gray-400)',
        'gray-500': 'var(--iq-gray-500)',
        'gray-600': 'var(--iq-gray-600)',
        'gray-700': 'var(--iq-gray-700)',
        'gray-800': 'var(--iq-gray-800)',
        'gray-900': 'var(--iq-gray-900)',
      },
      screens: {
        xs: '520px',
        '3xl': '1720px',
        wd: '1600px',
      },
      boxShadow: {
        'iq-navbar': '0 4px 8px rgba(0,0,0,.03)',
        'iq-sidebar': '1px 0px 10px rgba(0,0,0,.05)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
}
