import type { Insight } from '../../types/insight'
import InsightRailItem from './InsightRailItem'

type Props = {
  insights: Insight[]
  activeId: string
  onSelect: (id: string) => void
}

export default function InsightRail({ insights, activeId, onSelect }: Props) {
  return (
    <div
      className="flex w-[280px] flex-shrink-0 flex-col overflow-y-auto border-r border-color-hr bg-color-card px-5 py-6"
      style={{ height: 'calc(100vh - 64px)' }}
    >
      <p className="mb-3.5 text-sm font-semibold text-color-h2">
        Insights
      </p>

      <div className="flex flex-col gap-1.5">
        {insights.map((insight) => (
          <InsightRailItem
            key={insight.id}
            insight={insight}
            isActive={insight.id === activeId}
            onClick={() => onSelect(insight.id)}
          />
        ))}
      </div>

      <div className="mt-6 border-t border-color-hr pt-5">
        <p className="mb-2.5 text-sm font-semibold text-color-h2">
          Next up
        </p>
        <p className="text-xs leading-relaxed text-color-p">
          Delinquency exposure lands{' '}
          <span className="text-color-h2">Nov 15</span>
        </p>
      </div>

      <div className="mt-5 rounded-lg border border-dashed border-color-hr bg-color-stage p-3">
        <p className="text-[11px] leading-relaxed text-color-muted2">
          Insights are generated by{' '}
          <span className="text-color-h2">Databricks Genie</span> from your
          live portfolio data. New insight monthly.
        </p>
      </div>
    </div>
  )
}
